from .blacklist import blacklist
from .switchlist import switchlist
from .whitelist import whitelist
from .forcesave import forcesave
from .forcerestore import forcerestore
from .stats import stats
from .loggingcommand import logging
from .forgetme import forgetme
from .help import help
from .premium import premium